### ISSUE TITLE
Error: FIB table does not exist

### ISSUE THREAD

**Issue by yaa110** [shemminger/iproute2#32]
I am not sure that here is a good place to submit the issue, however it seems it is related to the latest version of `iproute2`:

```bash
# uname -a
Linux pc-name 5.7.17-2-MANJARO 1 SMP PREEMPT Sat Aug 22 14:58:17 UTC 2020 x86_64 GNU/Linux

# ip -V
ip utility, iproute2-v5.7.0-77-gb687d1067169

# ip r show table default 
Error: ipv4: FIB table does not exist.
Dump terminated
```

**Comment by dsahern** [comment]
Technically, that is due to a kernel not change, not iproute2.

The 'default' table does not exist by default (ironically). As of v4.20 the kernel has a strict mode. For routes, that strict mode means if a table does not exist the kernel tells you the table does not exist as opposed to silently sending nothing back.
